### ISSUE TITLE
About QM9 and NMC training

### ISSUE THREAD

**Issue by kk154** [AIforGreatGood/charge3net#3]
Can you tell me for the downloaded QM9 and NMC datasets, how do I process them for training,thanks

**Comment by kk154** [comment]
do I use the same steps as for the MP dataset?

**Comment by keeganq** [comment]
Thanks for bringing this to our attention! For both NMC and QM9 datasets, the data is downloaded in the `.tar` data format. We provide a [dataset](https://github.com/AIforGreatGood/charge3net/blob/961dc7e1dac0af9e47d308a0b750107c54040107/src/charge3net/data/dataset.py#L336) that supports loading the data directly from `.tar` files.

However, there is some minor additional preprocessing to create the `data_root` and `split_file` needed in the configs for running training. I'll push some additional instructions shortly, since they will be different than the MP dataset.

**Comment by keeganq** [comment]
@kk154 The latest merged PR should have resolved this issue. Please let me know if you're still having problems preprocessing QM9 and NMC!
